mqtt:
  broker: "abc.com" #eg:"tcp://broker.emqx.io:1883"
  clientId: "testing_id"

#spring.data.mongodb:
#  uri: <mongodb_uri>
#  database: <database_name>

spring.data.mongodb:
#  host: "127.0.0.1"            # Not Working in docker
#  host: "0.0.0.0"              # For docker container
  host: "mongo.docker.db"          #eg: "host.docker.internal"  # For docker container
  port: 27017          # default 27017
  database: <mongodb_database_name>

# Socket.IO server configuration
socketio.server:
#  host: "localhost"            # Not Working in docker
  host:  <socketio_host_url>    # default:"0.0.0.0" # For Docker container
  port: <socketio_server_port>  # default 9092