name: "Build & Release Maven"

# Define when to trigger the workflow (on each push to the main branch)
## Whatever push changes occurs to main branch, this workflow will trigger.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Set the environment for this job (place where these workflow will run below steps and cmds)
    runs-on: ubuntu-latest
    steps:
      # Checkout to current
      - name: Checkout
        uses: actions/checkout@v4

      # Use the setup-java action to configure the Java environment
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'path'
        run: |
          ls -lrth
          ls /home/runner/work/IoT-Platform/
          ls /home/runner/work/IoT-Platform/IoT-Platform

      # Run Maven command to build the project
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true --file pom.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'path'
        run: |
          ls -lrth
          ls /home/runner/work/IoT-Platform/
          ls -lrth /home/runner/work/IoT-Platform/target/
      # Use the softprops/action-gh-release action to create a GitHub release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GIT_ACTION_PAT }}
          tag_name: ReleaseBase
          files: target/*.jar # Specify the files to be included in the release (JAR files in the target directory)